# services/etl/Dockerfile
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install netcat
RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean
RUN pip install --upgrade pip

COPY . .

# Add wait script
RUN chmod +x wait-for-kafka.sh

CMD ["./wait-for-kafka.sh", "etl.py"]

#CMD ["python", "etl.py"]
