# services/api/Dockerfile
FROM python:3.10-slim

WORKDIR /app

COPY services/api/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Install dependencies  
RUN pip install --no-cache-dir torch transformers

#COPY services/api/wait-for-kafka.sh ./wait-for-kafka.sh

COPY . .
COPY services/database/ ./database

ENV DB_PATH=claim_history.duckdb

ENV PYTHONPATH="${PYTHONPATH}:/app/.."

# Make wait script executable
RUN chmod +x ./services/api/wait-for-kafka.sh

#ENV PYTHONPATH="${PYTHONPATH}:api:/app/shared"
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD [ "./services/api/wait-for-kafka.sh", "uvicorn", "services.api.main:app", "--host", "0.0.0.0", "--port", "8000"]