# services/frontend/Dockerfile
FROM python:3.10-slim

WORKDIR /app

COPY services/frontend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Install dependencies
RUN pip install --no-cache-dir torch transformers

ENV DOCKER=1


COPY . .
#COPY services/database/ ./database
COPY services /app/services

ENV DB_PATH=claim_history.duckdb
ENV PYTHONPATH="${PYTHONPATH}:/app/.."

EXPOSE 8501

#ENV PYTHONPATH="${PYTHONPATH}:frontend:/app/shared"
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
